### ISSUE TITLE
Questions about Package

### ISSUE THREAD

**Issue by axisiscool** [chaos-core/chaos-core#34]
Hello!

I had a quick question after reading #32 
Is there a way to make a plugin guild only? Like make it so one guild can run that group of commands and no others can? Thanks for any help

**Comment by Zeragamba** [comment]
No prob. In the command you can check that `context.guild.id` matches the id for the guild you want to limit the command too.

**Comment by yaboyaxis** [comment]
hey again... this doesn't work with DJS 12 right? I tried with it and it gave a lot of errors.

**Comment by Zeragamba** [comment]
Oh, ya sorry. I need to get around to actually updating to Discord.js 12, though it's hard to write integration tests with it.

**Comment by yaboyaxis** [comment]
ok cool... just didnt know if u were aware of it, i guess ill either wait or settle for DJS 11 for now, just wouldnt like to cuz of no support
